bgruening/galaxytools

rna_tools/trna_prediction/aragorn.xml, rna_tools/trna_prediction/aragorn_out_to_gff3.py, rna_tools/trna_prediction/test-data/aragorn_tansl-table-1_tmRNA_tRNA.gff3, rna_tools/trna_prediction/tool_dependencies.xml
This is really awful horrible code, I'm aware. However, their output is likewise, really awful and horrible.
We make the decision to run aragorn twice, once with forced output formatting if GFF3 is requested, as it's easier than the alternative. (The alternative is, of course, to run once with 'full' format, and then generate the fasta version if they'd rather have that from the 'full').
=> Aragorn output to useful GFF3

blockbuster/blockbuster.xml, segemehl/segemehl.xml
=> Segemehl bugfix and adding citations.

CONTRIBUTING.md
Describes how to fork, pull request, etc.... Github will display a link to this information in certain contexts and even if it didn't it can be very useful to potential developers.
=> Outline a CONTRIBUTING file for this repository.

diamond/repository_dependencies.xml
A # symbol in front of --bismark_path messed up the command line so the caller didn't run in galaxy.
All the best
Cristian
=> Fix bug in bismark_methylation_caller.xml

packages/package_fiji_20141125/tool_dependencies.xml
I'll have a tool following shortly after this gets merged.  Thanks!
=> Add a recipe for installing version 20141125 of the fiji package.

packages/package_fiji_20141125/.shed.yml, packages/package_imagej_1_48/.shed.yml, packages/package_imagej_1_48/tool_dependencies.xml, packages/package_javabridge_1_0_11/.shed.yml, packages/package_python_bioformats_1_0_4/.shed.yml
package_javabridge_1_0_11 and package_python_bioformats_1_0_4.  Also add
an additional environment variable for the package_imagej_1_48 recipe
(although the recipe may not be used since we now have fiji, the
environment variable is very usefule).
=> Add .shed.yml files for package_fiji_20141125, package_imagej_1_48,

tools/segemehl/.shed.yml, tools/segemehl/segemehl.xml, tools/segemehl/tool_dependencies.xml
=> update segemehl to version 0.2

tools/rna_tools/dorina/.shed.yml
No problem, it's on the main toolshed now.
=> Make uploadable with planemo.

visualisations/dbgraph/templates/dbgraph.mako
This is a small step towards interactive structure modification
=> Adds input field with sequence & dotbracket

tools/image_processing/imagej2/imagej2_bunwarpj_align/imagej2_bunwarpj_align.xml, tools/image_processing/imagej2/imagej2_convert_format/imagej2_convert_format.xml
copy of the tool config in my initial commit.  I assume some tests have
failed somehwere - very sorry!
=> Fixes for functional tests for 2 imagej tools - I somehow got the wrong

tools/image_processing/imagej2/imagej2_base_utils.py, tools/image_processing/imagej2/imagej2_bunwarpj_align/imagej2_bunwarpj_align.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compare_elastic/.shed.yml, tools/image_processing/imagej2/imagej2_bunwarpj_compare_elastic/imagej2_bunwarpj_compare_elastic.xml, tools/image_processing/imagej2/imagej2_bunwarpj_convert_to_raw/imagej2_bunwarpj_convert_to_raw.xml, tools/image_processing/imagej2/imagej2_bunwarpj_elastic_transform/imagej2_bunwarpj_elastic_transform.xml, tools/image_processing/imagej2/imagej2_bunwarpj_raw_transform/imagej2_bunwarpj_raw_transform.xml, tools/image_processing/imagej2/imagej2_convert_format/imagej2_convert_format.xml, tools/image_processing/imagej2/imagej2_create_image/imagej2_create_image.xml, tools/image_processing/imagej2/imagej2_macros.xml, tools/image_processing/imagej2/imagej2_noise/imagej2_noise.xml
imagej2_base_utils.get_max_heap_size_value() function, and fix the id of
the bunwarpj_compare_elastic tool.
@bgruening sorry about screwing up the id of the imagej2_bunwarpj_compare_elastic tool.  :(
=> Enhance macro use in the imagej2 tools, fix an intermittent bug in the

tools/rna_tools/sortmerna/sortmerna.xml, tools/rna_tools/sortmerna/tool-data/rRNA_databases.loc.sample
Testing indexed databases and output filtering has obviously uncovered a few bugs, but after merging this I think pushing to the main TS should be fine.
=> SortMeRNA: fix use of indexed databases and output filtering.

tools/image_processing/imagej2/readme.md
@bgruening Hope this looks ok for now - let me know if you see anything you don't like and I'll update.  I'm planning to keep this current with additional tools.
=> First pass at document for ImageJ2 tools.

tools/homer/tools/makeTagDirectory.xml, tools/piranha/piranha.xml, tools/sqlite_merger/sqlite_merger.xml, tools/suspenders/suspenders.xml
In support of https://github.com/galaxyproject/tools-iuc/issues/239
=> Swap all repeats to multiple='True' where appropriate

tools/text_processing/text_processing/grep.xml, tools/text_processing/text_processing/test-data/egrep1.txt, tools/text_processing/text_processing/test-data/egrep_results1.txt
Hi @bgruening,
I'm used to work with egrep / grep -E so I thought why not including it. I don't know what the additional value to you is, but if you like it you can merge.
I am missing grep in Galaxy. Could you get it into the toolshed or is there still work that to be done apart from the small list in the readme?
thanks in advance,
Youri
=> Support for basic and extended grep

tools/uniprot_rest_interface/uniprot.xml
Fixes https://github.com/bgruening/galaxytools/issues/256
=> Include txt download from uniprot

tools/rpy_statistics_collection/tool_dependencies.xml
@bgruening also it might be a good idea to use owner iuc?
=> Fix version number of rpy2

tools/rna_tools/sortmerna/sortmerna.xml, tools/trim_galore/trim_galore.xml
These show up as WARNINGs in the Galaxy log at every server restart.
=> Fix missing and wrong <when>s.

tools/rna_tools/sortmerna/sortmerna.xml, tools/rna_tools/sortmerna/tool-data/rRNA_databases.loc.sample, tools/rna_tools/sortmerna/tool_dependencies.xml
To fix #272:
* Add parameters that was lacking
* Add specific commands to install on MacOSX
=> Upgrade the Sortmerna wrapper

tools/trim_galore/trim_galore.xml
Thanks to Thomas Berner for spotting this!
=> Correct unpaired read output

tools/mafft/mafft.xml
Fix bug introduced in commit f1c0bd85086a7a2dbe125a251a509aef4f754794.
=> Move "ep" outside custom flavour also in command.

tools/sklearn_tools/discriminant.xml, tools/sklearn_tools/eden_vectorizer.xml, tools/sklearn_tools/main_macros.xml, tools/sklearn_tools/nn_classifier.xml, tools/sklearn_tools/numeric_clustering.xml
- numeric_clustering is now able to process sparse vector format as well as normal tabular data.
- enen_vectorizer is explicitly storing results in mtx format.
- plus some changes to reduce the size of wrappers by using macros.
=> Scipy toolkit

tools/sklearn_tools/numeric_clustering.xml
Now the output reflects the actual numeric labels (no header).
=> Pandas format correction in outfile.

.tt_blacklist, tools/trim_galore/.shed.yml, tools/trim_galore/trim_galore.xml
=> handle compressed files in trim galore

tools/sklearn_tools/main_macros.xml
main_macros updated with param macros of linear_model classifier.
=> Parameter macros for linear_model added to main_macros.

.tt_blacklist, tools/blockbuster/blockbuster.xml
@pavanvidem @dmaticzka isn't this beautiful?
https://travis-ci.org/bgruening/galaxytools/builds/117585931
=> Blockbuster testing

.travis.yml
=> Add automatic Tool Shed upload to travis

.travis.yml
I found a conda based planemo much more stable than the pip one. Let's test this on travis as well.
=> Switch over to conda based planemo install

.travis.yml
Reverts bgruening/galaxytools#320
=> Revert "Switch over to conda based planemo install"

tools/sklearn_tools/numeric_clustering.xml
Numeric_clustering with coulmn_data in "inputs" configfile.
=> numeric_clustering tailored for column_data.

tools/sklearn_tools/main_macros.xml, tools/sklearn_tools/nn_classifier.xml, tools/sklearn_tools/numeric_clustering.xml
Consistency-check updates on tools.
=> nn_classifier temporary rollbacks. clustering update.

.tt_blacklist, tools/find_subsequences/find_subsequences.xml, tools/find_subsequences/test-data/find_subsequences_advanced_result2.bed, tools/find_subsequences/test-data/find_subsequences_advanced_result3.bed
Add the comment to let people know the requirement will try to be resolved using BioPython Conda: https://anaconda.org/anaconda/biopython
=> Comment for BioPython Conda

tools/rna_tools/sortmerna/sortmerna.xml
I got error when running SortMeRNA with Blast output, due to the new SortMeRNA version (changes in options). So I tried to fix that
I also add missing inputs in current tests
=> Fix SortMeRNA for Blast output

tools/sailfish/sailfish.xml, tools/sailfish/tool_dependencies.xml
based on comment from @mvdbeek https://github.com/galaxyproject/tools-iuc/issues/947#issuecomment-247701136
=> condafi sailfish

tools/trim_galore/trim_galore.xml
=> add new xml wrapper with the modified help section

tools/text_processing/text_processing/.shed.yml, tools/text_processing/text_processing/awk.xml, tools/text_processing/text_processing/cat.xml, tools/text_processing/text_processing/easyjoin.xml, tools/text_processing/text_processing/find_and_replace.xml, tools/text_processing/text_processing/grep.xml, tools/text_processing/text_processing/multijoin, tools/text_processing/text_processing/multijoin.xml, tools/text_processing/text_processing/replace_text_in_column.xml, tools/text_processing/text_processing/replace_text_in_line.xml, tools/text_processing/text_processing/sed.xml, tools/text_processing/text_processing/sort.xml, tools/text_processing/text_processing/sorted_uniq.xml, tools/text_processing/text_processing/unfold_column.xml
=> Use new sed Conda package. Linting fixes. Fix requirements

chemicaltoolbox/chemfp/chemfp_clustering/butina_clustering.xml
=> butina_clustering

chemicaltoolbox/ctb_machine_learning/mds_plot.xml
=> fragmenter

tools/bigwig_to_bedgraph/bigwig_to_bedgraph.xml
fixed linting for bigwig_to_bedgraph
=> bigwig_to_bedgraph

chemicaltoolbox/spectral_hk/spectral_hk.xml
=> spectral_hk

.tt_blacklist
In this case only under linting
=> Get Dorina under testing

tools/rna_tools/vienna_rna/macros.xml, tools/rna_tools/vienna_rna/rnaalifold.xml, tools/rna_tools/vienna_rna/rnacofold.xml
=> vienna_rna

tools/rpy_statistics_collection/cca.xml, tools/rpy_statistics_collection/cor.xml, tools/rpy_statistics_collection/gsummary.xml, tools/rpy_statistics_collection/histogram.xml, tools/rpy_statistics_collection/kcca.xml, tools/rpy_statistics_collection/kpca.xml, tools/rpy_statistics_collection/linear_regression.xml, tools/rpy_statistics_collection/logistic_regression_vif.xml, tools/rpy_statistics_collection/partialR_square.xml, tools/rpy_statistics_collection/pca.xml, tools/rpy_statistics_collection/scatterplot.xml, tools/rpy_statistics_collection/short_reads_figure_score.xml, tools/rpy_statistics_collection/statistic_tools_macros.xml
fixed linting for py_statistics_collection
=> py_statistics_collection

tools/image_processing/imagej2/.shed.yml
ping @gregvonkuster @ThomasWollmann 
This will kickstart a Galaxy-Imaging community :)
=> Change to imgteam

tools/openms/PeakPickerHiRes.xml, tools/openms/readme.md
Fix for PeakPickerHiRes. Check OpenMS/OpenMS#2358 for more details.
=> Fix for PeakPickerHiRes

tools/openms/macros.xml
=> making deps more explicit

tools/openms/macros.xml
Fixed with latest conda package for OpenMS
=> Remove boost dependency from wrapper

tools/methyldackel/tool_dependencies.xml
=> maybe explicitly create a bin directory?

tools/GraphClust/CMFinder/cmFinder.xml, tools/GraphClust/CollectResults/glob_report.xml, tools/GraphClust/GSPAN/fasta2shrep_gspan.xml, tools/GraphClust/LocARNAGraphClust/locarna_best_subtree.xml, tools/GraphClust/NSPDK/NSPDK_candidateClusters.xml, tools/GraphClust/NSPDK/NSPDK_sparseVect.xml, tools/GraphClust/PrepareForMlocarna/preMlocarna.xml, tools/GraphClust/Preprocessing/preprocessing.xml
graphclust version update and combined cmsearch output added to collect_results. 
@bgruening, my travis test is failing again, and it seems reason is the same as before. What did you do last time that it passed?
=> graphclust version update

tools/rna_tools/sortmerna/sortmerna.xml
Hi,
I fix a bug in command options used for paired inputs.
=> Sortmerna fix command options

tools/diffbind/diffbind.xml
Bumb wrapper version (correct?).
=> Add r-getopt as requirement.

tools/salmon/salmon.xml
Also put the version in a token, for easier future upgrades
=> Upgrade to salmon 0.8.2

chemicaltoolbox/openbabel/macros.xml
=> add pdb to the openbabel xml macro

tools/trim_galore/trim_galore.xml
=> shows warnings to give a user a fighting chance

.travis.yml, tools/trim_galore/trim_galore.xml
Follow-up to https://github.com/bgruening/galaxytools/pull/332 .
=> Use decompress attribute introduced in 17.05

data_managers/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.py, data_managers/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.xml, data_managers/data_manager_sortmerna_database_downloader/data_manager_conf.xml, data_managers/data_manager_sortmerna_database_downloader/tool-data/rRNA_databases.loc.sample, data_managers/data_manager_sortmerna_database_downloader/tool_data_table_conf.xml.sample, tools/rna_tools/sortmerna/sortmerna.xml, tools/rna_tools/sortmerna/tool-data/rRNA_databases.loc.sample, tools/rna_tools/sortmerna/tool_data_table_conf.xml.sample
Hi,
As mentioned by @nsoranzo in #587, I removed the `dbkey` column in the data table to avoid conflicts with old installations.
Bérénice
=> Fix SortMeRNA data manager

tools/salmon/salmon.xml
spotted in @malloryfreeberg talk at GCC
=> salmon help fix

tools/text_processing/text_processing/awk.xml
Referring to resolve issue https://github.com/bgruening/galaxytools/issues/600#issuecomment-313335129
=> Add BEGIN & FS examples

tools/text_processing/text_processing/multijoin.xml
Let's collect here a few enhancements to the text-processing tools.
ping @blankenberg @jennaj
=> WIP: Update text-processing tools

tools/segemehl/segemehl.xml
Minor change, multi data input probably with new version
=> Allow single read input files

tools/rna_tools/intarna/intarna.xml
fixes: https://github.com/bgruening/galaxytools/issues/624
=> IntaRNA update to 2.0.4

tools/rna_tools/intarna/intarna.xml
As far as I understood it the file format should be txt (not txt).
=> intarna: format text -> txt

tools/rna_tools/vienna_rna/rnacofold.xml, tools/rna_tools/vienna_rna/rnafold.xml
@bgruening Could you have a look if I did the sanitation disable correct please, thanksalot
=> Rnafold constraint fix

tools/rna_tools/vienna_rna/rnafold.xml
@bgruening hope this does not break anything
=> Working on simultaneous usage of mea and partfunc

tools/text_processing/text_processing/replace_text_in_line.xml
=> Fix sed tool

tools/antismash/antismash.xml, tools/antismash/test-data/ARBH01000003.1.cluster001, tools/antismash/test-data/index.2.html, tools/antismash/test-data/index.html
=> update to 4.1

tools/sklearn/clf_metrics.xml, tools/sklearn/ensemble.xml, tools/sklearn/generalized_linear.xml, tools/sklearn/main_macros.xml
In such a way, it gives the inputs more flexibility, for example, allowing headers in the input file.
=> change the COLUMNS_FUNCTION to accept args

tools/bismark/bismark_methyl_extractor/bismark_methylation_extractor.py, tools/bismark/bismark_methyl_extractor/bismark_methylation_extractor.xml
the raise syntax is invalid... fixes that.
Not sure about the version number bump... but usually i forget that;)
=> Meth extractor raise fix

tools/rna_tools/intarna/intarna.xml, tools/rna_tools/intarna/test-data/intarna_result.tabular
- "old" intarna package was build with buggy vrna version
=> bump wrapper due to updated 2.1.0 bioconda package

tools/sklearn/discriminant.xml, tools/sklearn/ensemble.xml, tools/sklearn/generalized_linear.xml, tools/sklearn/main_macros.xml, tools/sklearn/nn_classifier.xml, tools/sklearn/numeric_clustering.xml, tools/sklearn/svm.xml
The tool took header by default was a trick. 😸
=> Apply new dataset input system to sklearn tools

tools/sklearn/main_macros.xml, tools/sklearn/model_validation.xml, tools/sklearn/search_model_validation.xml
The Penn paper used object as input rather than none/int.
=> add object eval for CV input and make randomness possible in cv splitting

tools/sklearn/pipeline.xml, tools/sklearn/search_model_validation.xml
1. replace the scoring name `primary` with the original sklearn name
2. add couple of tests to test the security feature of text input box
=> change searchcv primary scoring and add a few tests for text box

.travis.yml, tools/chipseeker/chipseeker.R, tools/chipseeker/chipseeker.xml
And add ignore upstream and downstream options
=> Update chipseeker to v1.18.0

tools/bismark/bismark_bowtie2_wrapper.xml
Just a little typo found while looking for another bug (which was not there)
=> Bismark: fix typo

tools/plotly_ml_performance_plots/plot_ml_performance.py
This PR corrects the axes labels in the confusion matrix plot
=> Correct axes labels

tools/sklearn/main_macros.xml
could also be "EXCEPTING" or "BUT NOT some"
=> Maybe this is more readily understandable?

tools/bismark/bismark_bowtie2_wrapper.xml, tools/bismark/test-data/summary.txt, tools/bismark/test-data/summary_mate.txt, tools/bismark/test-data/summary_short.txt
Hopefully this should fix the failing tests from #881
=> Bismark: fix tests

chemicaltoolbox/openbabel/macros.xml, chemicaltoolbox/openbabel/ob_convert.xml, chemicaltoolbox/openbabel/test-data/split1.pdbqt, chemicaltoolbox/openbabel/test-data/split2.pdbqt
Modify openbabel convert tool to allow splitting multimolecule files.
=> Changes to convert tool

tools/sklearn/feature_selection.xml, tools/sklearn/generalized_linear.xml, tools/sklearn/main_macros.xml, tools/sklearn/ml_visualization_ex.py, tools/sklearn/ml_visualization_ex.xml, tools/sklearn/model_validation.xml, tools/sklearn/search_model_validation.xml, tools/sklearn/stacking_ensembles.py, tools/sklearn/train_test_eval.xml
Also refactored the input options.
=> fix generalized_linear tool fail to load header option

tools/rna_tools/intarna/intarna.xml, tools/rna_tools/intarna/test-data/intarna_result.tabular
- correction of additional output file handling (broken since 2.0.1)
- multi-threading support
- additional parameters enabled
- obsolete parameters and options removed
=> new IntaRNA 3.1.1 features

tools/salmon/alevin.xml
I suspect that this will fix #921
=> Remove curly-braces from cheetah if in Alevin

tools/rna_tools/paralyzer/paralyzer.xml
fixes: https://github.com/bgruening/galaxytools/issues/926
=> fix: https://github.com/bgruening/galaxytools/issues/926

tools/plotly_parallel_coordinates_plot/paracords_plot.py, tools/plotly_parallel_coordinates_plot/paracords_plot.xml
I think it will be more friendly in workflow.
=> make paracords plot to take header names

tools/sklearn/simple_model_fit.py
For security reason, remove support of estimators that contain file write handler.
Maybe need a warning?
=> Clean model params before fitting

tools/image_processing/graphicsmagick/convert.xml
solves https://github.com/galaxyproject/tools-iuc/issues/2477
=> gm-convert: add pdf support

tools/rna_tools/graphprot/graphprot_predict_wrapper.py, tools/rna_tools/graphprot/graphprot_train_predict.xml
Small error fix, to put out correct numbers of output files
=> Graphprot fix

tools/rna_tools/intarna/intarna.xml
[bioconda upload](https://github.com/bioconda/bioconda-recipes/runs/420126221) currently running ...
=> bump to v3.1.5 (bugfix release)

chemicaltoolbox/sucos/sucos.py, chemicaltoolbox/sucos/sucos_max.py, chemicaltoolbox/sucos/sucos_max.xml
The includes @bgruening 's change for better error handling (slightly improved) and merges the max and cumulative modes to be consistent with newer versions of the tool.
=> better error handling and combining max and cum modes

chemicaltoolbox/sucos/sucos_max.py, chemicaltoolbox/sucos/sucos_max.xml
Attempted fix for the SuCOS_Max failures
=> attempt to fix failure due to ZeroDivisionError

tools/cellprofiler/common.xml, tools/cellprofiler/test-data/common.txt, tools/cellprofiler/test-data/convert_objects_to_image.txt, tools/cellprofiler/test-data/display_data_on_image.txt, tools/cellprofiler/test-data/enhance_or_suppress_features.txt, tools/cellprofiler/test-data/export_to_spreadsheet.txt, tools/cellprofiler/test-data/gray_to_color.txt, tools/cellprofiler/test-data/identify_primary_objects.txt, tools/cellprofiler/test-data/mask_image.txt, tools/cellprofiler/test-data/measure_granularity.txt, tools/cellprofiler/test-data/measure_image_area_occupied.txt, tools/cellprofiler/test-data/measure_image_intensity.txt, tools/cellprofiler/test-data/measure_image_quality.txt, tools/cellprofiler/test-data/measure_object_intensity.txt, tools/cellprofiler/test-data/measure_object_size_shape.txt, tools/cellprofiler/test-data/measure_texture.txt, tools/cellprofiler/test-data/relate_objects.txt, tools/cellprofiler/test-data/save_images.txt
update 'select folder regex' to use 'select' instead of text. similar to the file regex implementations in the same module
=> change folder name regex in NameAndTypes module in common.xml

chemicaltoolbox/sucos/sucos_max.py, chemicaltoolbox/sucos/sucos_max.xml
Simple addition that avoid the need for running another tool to filter the output.
=> add filtering to sucos max

tools/mafft/macros.xml, tools/mafft/mafft.xml
=> new mafft version

tools/salmon/macros.xml, tools/salmon/salmonquant.xml
And leaving this at bam fails the metadata job because the file can't be
indexed.
=> Bam output from salmon quant is unsorted

tools/cellprofiler/starting_modules.xml, tools/cellprofiler/test-data/common-nogroup.txt
- added py code for condition grouping=no
- added test case accordingly
@beatrizserrano
=> fix bug in starting_modules.xml when grouping=no

tools/text_processing/split_file_to_collection/split_file_to_collection.py, tools/text_processing/split_file_to_collection/split_file_to_collection.xml
by only opening one file at a time
fixes https://github.com/bernt-matthias/galaxytools/pull/new/topic/split-many
=> split_file_to_collection: allow large number of files

tools/sklearn/train_test_split.xml
improved help a bit for better understanding of nth_split usage
=> sklearn train_test_split

chemicaltoolbox/pgchem/pgchem/db_similarity_search.xml
just stumbled over this one. 
would need a loc file to make the test work... any suggestions @bgruening ?
=> fixes for pgchem

tools/text_processing/text_processing/cat.xml
Supposedly fixes https://github.com/galaxyproject/galaxy/issues/10176
=> Allow some gzipped input types to cat

tools/text_processing/add_line_to_file/.shed.yml, tools/text_processing/add_line_to_file/add_line_to_file.xml, tools/text_processing/add_line_to_file/test-data/add_line.txt, tools/text_processing/add_line_to_file/test-data/add_line_result1.txt, tools/text_processing/add_line_to_file/test-data/add_line_result2.txt
A simple tool for adding a text line at the beginning (or the end) of a file.
=> Add line to file tool

.github/workflows/pr.yaml
Cherry-picked from https://github.com/bgruening/galaxytools/pull/1048 as I need it for another PR.
=> Update PR CI

tools/bismark/bismark_bowtie2_wrapper.xml
Replace --non-directional by --non_directional
=> fix non directional parameter

tools/diff/diff.xml
Hello! This is an automated update of the following tool repo: **tools/diff**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/diff tool version(s)

tools/mafft/macros.xml
Hello! This is an automated update of the following tool repo: **tools/mafft**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/mafft tool version(s)

README.md
=> Added documentation for getting tools into Galaxy

tools/nanopolish/nanopolish_eventalign.xml
As mentioned before @bgruening !
=> expose --signal-index option in the wrapper

tools/bionano/bionano_scaffold.xml, tools/bionano/macros.xml
This PR updates the outputs; scaffolded and not scaffolded files are provided independently instead of concatenating them. It also provides the conflict.txt file as output.
=> Bionano modify outputs

tools/flye/flye.xml
=> Made asm parameter optional in flye

tools/text_processing/text_processing/cat.xml
changes the way files are concating, now appending files one by one instead of altogether to avoid large command when a collection is too big
=> changes the way files are concating, now appending files one by one instead of altogether

chemicaltoolbox/autodock_vina/prepare_box/calc_vina_box_params.py, chemicaltoolbox/autodock_vina/prepare_box/prepare_box.xml
Strict parsing and sanitization of the input files is not that important - we just want to get the coordinates and get the average.
=> Fix for prepare_box

tools/racon/macros.xml, tools/racon/racon.xml
must be fastq/fasta but they aren't for fastqsanger ...
fixes https://github.com/galaxyproject/tools-iuc/issues/3856
=> racon: fix file extensions

chemicaltoolbox/silicos-it/align-it/align-it.xml
* a test for a real phar datatype is needed
=> make phar datatype work for alignit, update to 1.0.4

tools/racon/macros.xml
Hello! This is an automated update of the following tool repo: **tools/racon**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/racon tool version(s)

tools/peakachu/peakachu.xml
This PR updates Peakachu up to version 0.2.0 and fixes a but in the _--size_factors_ parameter.
=> Update Peakachu v0.2.0

tools/rna_tools/intarna/intarna.xml
Hi @bgruening 
please have a look if the additional (optional) `--outPairwise` argument is correctly integrated into the xml.
Thanks,
Martin
=> IntaRNA v3.3.1 + new option "--outPairwise"

tools/rna_tools/intarna/intarna.xml
already merged into bioconda but currently uploaded to conda (not available as of right now)
=> bump intarna v3.3.2

tools/gfastats/gfastats.xml, tools/gfastats/macros.xml, tools/gfastats/test-data/test_07_stats.tabular, tools/gfastats/test-data/test_12_stats.tabular
gfastats version bump from 1.3.0 to 1.3.3
=> version bump 1.3.4

tools/gfastats/macros.xml
=> gfastats version bump 1.3.5

tools/rna_tools/graphprot/.shed.yml
Add CLIP-seq toolshed category
=> add toolshed category

tools/gfastats/macros.xml, tools/rna_tools/locarna/macros.xml, tools/salmon/macros.xml
to deploy these tools (xref https://github.com/bgruening/galaxytools/pull/1271)
=> artificial bump

tools/jupyter_job/run_jupyter_job.xml
The container's version also changes here.
ping @bgruening Thank you!
=> Update container version for remote training tool

tools/hifiasm/hifiasm.xml
=> hifiasm: version bump 0.19.3

tools/mitohifi/macros.xml, tools/mitohifi/mitohifi.xml
updating docker link to the new mitohifi version + adding some new outputs introduced in v3
=> mitohifi version bump to v3

tools/hifiasm/hifiasm.xml
👋🏼 version bump to 0.19.5 for hifiasm!
=> hifiasm: version bump 0.19.5

tools/racon/macros.xml, tools/racon/racon.xml
Added GPU parameters for racon to allow execution of the GPU supported version of racon.
=> Adding GPU parameters for racon

tools/salmon/macros.xml, tools/salmon/salmonquant.xml
Hi, salmon quant is failing on GA with paired_interleaved input. I guess it's not used very often but it seems to just be quoting, so I fixed it and added a test.
=> paired_interleaved

tools/sklearn/keras_batch_models.xml, tools/sklearn/ml_visualization_ex.py, tools/sklearn/ml_visualization_ex.xml
I think these changes got missed during the upgrade to Galaxy ML 0.10.0
ping @bgruening
=> Fix ML visualisation tool reg confusion matrix

tools/rna_tools/rbpbench/macros.xml
Update wrapper to RBPBench 0.8.1
=> update to v081

tools/hifiasm/hifiasm.xml
=> hifiasm: fix typo in param documentation

.github/styler.R, tools/text_processing/text_processing/awk.xml, tools/text_processing/text_processing/cat.xml, tools/text_processing/text_processing/cut.xml, tools/text_processing/text_processing/easyjoin.xml, tools/text_processing/text_processing/find_and_replace.xml, tools/text_processing/text_processing/grep.xml, tools/text_processing/text_processing/head.xml, tools/text_processing/text_processing/macros.xml, tools/text_processing/text_processing/multijoin.xml, tools/text_processing/text_processing/nl.xml, tools/text_processing/text_processing/recurring_lines.xml, tools/text_processing/text_processing/replace_text_in_column.xml, tools/text_processing/text_processing/replace_text_in_line.xml, tools/text_processing/text_processing/sed.xml, tools/text_processing/text_processing/sort.xml, tools/text_processing/text_processing/sort_rows.xml, tools/text_processing/text_processing/sorted_uniq.xml, tools/text_processing/text_processing/tac.xml, tools/text_processing/text_processing/tail.xml, tools/text_processing/text_processing/test-data/grep_results2.html, tools/text_processing/text_processing/test-data/nl-out-number-format.txt, tools/text_processing/text_processing/test-data/nl-out.txt, tools/text_processing/text_processing/test-data/nl-start-incr.txt, tools/text_processing/text_processing/unfold_column.xml, tools/text_processing/text_processing/unsorted_uniq.xml
merges in https://github.com/bgruening/galaxytools/pull/1375 and https://github.com/bgruening/galaxytools/pull/1376
=> update text processing tools

tools/cellpose/cellpose.xml
Update Cellpose wrapper name and description according to the [tool naming & description convention of the image community](https://github.com/elixir-europe/biohackathon-projects-2023/blob/main/16/paper/paper.md#conventions)
Sorry I don’t want to come off as picky, but I think that we agreed on some conventions to have a standard which unifies the overall structure of tools in our community, to improve their findability.
=> Update Cellpose wrapper name and description

tools/lighter/.shed.yml, tools/lighter/lighter.xml
This PR links lighter to its bio.tools [entry](https://bio.tools/lighter).
=> Added bio.tools ref to lighter

tools/nucleosome_prediction/nucleosome_prediction.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/nucleosome_prediction
It will be useful to get EDAM ontology annotations
Have a good day!
=> add bio.tools for nucleosome prediction

tools/graphmap/graphmap_align.xml, tools/graphmap/graphmap_owler.xml, tools/graphmap/macros.xml
Hi all,
This PR links the tools to its bio.tools entry: https://bio.tools/graphmap
It will be useful to get EDAM ontology annotations
Engy
=> Add bio.tools for graphmap

tools/biomodelsML/biomodels_BIOMD0000001066.xml, tools/biomodelsML/biomodels_BIOMD0000001076.xml, tools/biomodelsML/macros.xml
This PR:
- Make tool ids consistent
- Use Docker container from quay.io/galaxy repository
- Move common things to `macro.xml`
=> [WIP] Fix BioModels tools and include macro

tools/text_processing/split_file_to_collection/.shed.yml, tools/text_processing/split_file_to_collection/split_file_to_collection.py, tools/text_processing/split_file_to_collection/split_file_to_collection.xml, tools/text_processing/split_file_to_collection/test-data/split_file_0.tabular, tools/text_processing/split_file_to_collection/test-data/split_file_1.tabular, tools/text_processing/split_file_to_collection/test-data/split_file_2.tabular, tools/text_processing/split_file_to_collection/test-data/split_file_3.tabular
This PR includes the following:
- added condition to write header in the final record dataset, it was not previously written in the last dataset if the chunk size was 1
- added test
closes #1424
=> Fix bug in split_file_to_collection

tools/cellprofiler_v4/.shed.yml, tools/cellprofiler_v4/macros.xml
Based on https://github.com/bgruening/galaxytools/pull/1468, updating the .shed file to debug the linting errors
=> Fixing Linting errors of cellprofiler_v4

tools/ear/macros.xml, tools/ear/make_EAR.py, tools/ear/make_EAR.xml, tools/ear/test-data/EAR.pdf, tools/ear/test-data/EAR_2.pdf
This pull request updates the **ERGA EAR** tool as per the recent changes made by @diegomics
---
Changes and Updates:
- Added a new Methods section to specify used tools along with version and tools parameters
- Updated make_ear.py script (Linting + Reformatting)
- Updated test data 
- Version Bump
@bgruening could you please review this?
=> Updating of the ERGA EAR tool

tools/ear/macros.xml, tools/ear/make_EAR.py
This PR updates the ERGA EAR tool with its new updated python script.
=> Update ERGA EAR tool to v24.10.15

tools/flux/flux.xml
Bug fix for FLUX tool: Torch not compiled with CUDA enabled
=> Add pytorch-cuda requirement to flux tool

tools/gfastats/macros.xml
This PR updates gfastats to its latest version based on bug reported in previous issue.
=> Update gfastats tool for bug fix

tools/music_deconvolution/construct_eset.xml, tools/music_deconvolution/inspect_eset.xml, tools/music_deconvolution/macros.xml, tools/music_deconvolution/manipulate_eset.xml, tools/music_deconvolution/music_compare.xml, tools/music_deconvolution/music_deconvolution.xml
Original PR was in mtekman/galaxytools, now putting it here @nomadscientist
=> Add bio.tools entry to MuSiC deconvolution tools 

tools/flux/flux.xml
Update package names and versions to ensure compatibility and resolve missing package issues.
=> Fix package requirements for Flux tool

tools/flye/flye.xml, tools/flye/macros.xml
And linter errors that will come with the new TestsCaseValidation linter
xref https://github.com/galaxyproject/tools-iuc/issues/6561
=> fix fly datatype

data_managers/data_manager_motus_db_downloader/tool-data/motus_db_versioned.loc.sample
Hi- this is just a small update for the Motus database.
=> Updated motus_db_versioned.loc.sample

.github/workflows/pr.yaml, tools/music_deconvolution/macros.xml, tools/music_deconvolution/music_compare.xml, tools/music_deconvolution/music_deconvolution.xml, tools/music_deconvolution/scripts/compare.R, tools/music_deconvolution/scripts/dendrogram.R, tools/music_deconvolution/scripts/estimateprops.R
Fix the following error when running on a Pulsar destination:
```
Fatal error: cannot open file '/jetstream2/scratch/main/jobs/65039573/tool_files/scripts/compare.R': No such file or directory
```
Also:
- Replace ubuntu-20.04 runner, see https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
- Lint R scripts with styler
=> Add missing required_files to run remotely

tools/text_processing/text_processing/awk.xml, tools/text_processing/text_processing/macros.xml, tools/text_processing/text_processing/recurring_lines.xml, tools/text_processing/text_processing/sort.xml
Makes it more useful for use in workflows. At the moment the allowed values are quite restricted.
=> parametrize awk tool

tools/canu/canu.xml
Guess this can go without a bump
=> canu: add docs for specifications file

tools/llm_hub/llm_hub.py, tools/llm_hub/llm_hub.xml
Introduce support for image models.
After this update image-to-text models like this could be add to the loc file:
```
numarkdown-8b-thinking-llmlb	Advanced OCR and document understanding, excels at extracting structured data from scanned images (NuMarkdown-8B-Thinking)	image	uni-freiburg	NuMind
```
=> Add handling for image models

.github/workflows/pr.yaml
Change the GALAXY_BRANCH environment variable to point to the new release version.
=> udpate CI integration
