bgruening/galaxytools

file_manipulation/uniq.xml
On a related point, the README file says "the uniq.xml and the sort_rows tools are moved to the unix tools" but I'm not sure where that is?
=> Fix uniq.xml typo by removing redundant help value

tools/rna_tools/trna_prediction/aragorn_out_to_gff3.py
The ID output by ARAGORN in the first column starts over at 1 with each
sequence-region, and so is not unique.
I've qualified each ID with the sequence it came from. The other way to fix this would be to simply assign each tRNA a sequential number.
=> aragorn_out_to_gff3.py: Make the GFF ID unique

tools/rna_tools/dorina/LICENSE, tools/rna_tools/dorina/data_source.py, tools/rna_tools/dorina/dorina.xml
Add a basic data source tool definition for the public DoRiNA
deployment.  When accessed with a GALAXY_URL parametre, DoRiNA offers a
link back to the provided Galaxy instance enabling it to fetch the
results in tabular form.
=> rna_tools: Add DoRiNA data source tool definition.

tools/rna_tools/trna_prediction/aragorn_out_to_gff3.py
Add product=tRNA-Met
This naming scheme is used by Refseq. For example:
Picea abies chloroplast complete genome
[NC_021456.1](http://www.ncbi.nlm.nih.gov/nuccore/523420621)
=> aragorn_out_to_gff3.py: Change Name to trnX-AAA

packages/package_fiji_20141125/tool_dependencies.xml
version 20141125 of the Fiji package.
=> Add a "stop-gap" fix for the Yosemite OS to the recipe for installing

tools/image_processing/imagej2/imagej2_adjust_threshold_binary/imagej2_adjust_threshold_binary.xml, tools/image_processing/imagej2/imagej2_adjust_threshold_binary/jython_script.py, tools/image_processing/imagej2/imagej2_analyze_particles_binary/imagej2_analyze_particles_binary.xml, tools/image_processing/imagej2/imagej2_analyze_skeleton/imagej2_analyze_skeleton.xml, tools/image_processing/imagej2/imagej2_analyze_skeleton/jython_script.py, tools/image_processing/imagej2/imagej2_bunwarpj_adapt_transform/imagej2_bunwarpj_adapt_transform.xml, tools/image_processing/imagej2/imagej2_bunwarpj_align/imagej2_bunwarpj_align.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compare_elastic/imagej2_bunwarpj_compare_elastic.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compare_elastic_raw/imagej2_bunwarpj_compare_elastic_raw.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compare_raw/imagej2_bunwarpj_compare_raw.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compose_elastic/imagej2_bunwarpj_compose_elastic.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compose_raw/imagej2_bunwarpj_compose_raw.xml, tools/image_processing/imagej2/imagej2_bunwarpj_compose_raw_elastic/imagej2_bunwarpj_compose_raw_elastic.xml, tools/image_processing/imagej2/imagej2_bunwarpj_convert_to_raw/imagej2_bunwarpj_convert_to_raw.xml, tools/image_processing/imagej2/imagej2_bunwarpj_elastic_transform/imagej2_bunwarpj_elastic_transform.xml, tools/image_processing/imagej2/imagej2_bunwarpj_raw_transform/imagej2_bunwarpj_raw_transform.xml, tools/image_processing/imagej2/imagej2_convert_format/imagej2_convert_format.xml, tools/image_processing/imagej2/imagej2_create_image/imagej2_create_image.xml, tools/image_processing/imagej2/imagej2_macros.xml, tools/image_processing/imagej2/imagej2_make_binary/imagej2_make_binary.xml, tools/image_processing/imagej2/imagej2_make_binary/jython_script.py, tools/image_processing/imagej2/imagej2_noise/imagej2_noise.xml, tools/image_processing/imagej2/imagej2_skeletonize3d/imagej2_skeletonize3d.xml, tools/image_processing/imagej2/imagej2_skeletonize3d/jython_script.py, tools/image_processing/imagej2/imagej2_watershed_binary/imagej2_watershed_binary.xml
1) Eliminate unnecessary imports from some Jython scripts
2) Make tool version string a macro
3) Eliminate version string from fiji and bioformats macro requirements
4) Move alert text for tools that require binary image inputs to a macro
5) Eliminate the ability to set output image formats - outputs will have
the same format as inputs
6) Move the adjust threshold command line arguments and parameters from
the macros to the tool config - I originally thought I may use these
across tools, but have since determined that is not needed.
=> General cleanup of ImageJ2 tools:

tools/text_processing/split_file_on_column/split_file_on_column.xml
Prevents other cruft in the job directory from being included in the collection list.
=> Have tp_split_on_column use a tmp directory for output. 

tools/sailfish/sailfish.xml
this is interpreted as a missing link by the parser
=> fix sailfish help

tools/diffbind/diffbind.xml
in addition reformatted a bit to make planemo lint happy. 
Generating test data is somewhat difficult, ran this on big samples which seemed to work as expected.
Basically this removes the control column when no control is found. It will however fail unclean when only a few samples have a control and some not... but I wasn't sure how much code can/should but squeezed in the configfile section
=> diffbind: optional control

tools/trim_galore/trim_galore.xml
This is still a bit hacky, but I've tested SE/PE/PE collections with both compressed and uncompressed files locally and everything seems to work. I guess if/when Galaxy starts supporting gzipped fastq files innately that a lot of scripts will need to start doing stuff like this.
=> Trim Galore! modifications for gzipped file handling

tools/image_processing/imagej2/imagej2_base_utils.py
No longer necessary since the introduction of the 20151222 conda install recipe for Fiji here https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fiji/20151222/bunwarpj.sh
=> Eliminate unnecessary env vars

tools/salmon/salmon.xml
Location of an '&&' in the <command> block followed by an optional indexing command causes an error if the indexing command is not called (using cached transcriptome) because two '&&' end up adjacent. Moving the first one inside the if block fixes this.
=> fixed bug when using cached transcriptome

tools/rna_tools/vienna_rna/rnafold.xml
the ps secondary structure drawing of the structures is not always needed. Skip option avoids large overhead of ps files generation and handling.
=> Option to skip ps drawing in rnafold

tools/methyldackel/MethylDackel.xml, tools/methyldackel/test-data/test_2.bedGraph, tools/methyldackel/tool_dependencies.xml
This is version 0.3.0, which supports multiple threads and detecting/avoiding likely SNPs. This also fixes a bug with methylation extraction from the last 1-3 bases in a contig.
=> Update methyl dackel

data_managers/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.py, data_managers/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.xml, data_managers/data_manager_sortmerna_database_downloader/data_manager_conf.xml, tools/rna_tools/sortmerna/sortmerna.xml
Hi,
I had some issues with SortMeRNA because of:
- Duplication of the values in the tool data table
- Incomplete copy of the indexed files
I also simplified the extraction of the path to the cached data in the SortMeRNA wrapper.
I ran some tests locally (using the data manager on the TTS). It worked...
Bérénice
=> (Another) Fix for the SortMeRNA data manager

tools/text_processing/text_processing/tac.xml
The help for `-s 5` was visually different from the other examples.
=> Minor cleanup of help text for tac.

tools/salmon/salmon.xml
Updated <outputs> and <command> sections. When --writeMappings is set to Yes/True, a SAM-formatted file is written to stdout and redirected to its own history item (name=output_sam).
NOTE: This filter condition (line 342) seems to always evaluate to True, even when writeMappings is False. Needs to be changed (I'm not sure what to) so that a SAM file isn't produced as output if writeMappings is set to 'No'/False. Any ideas, @bgruening ?
=> Enable stdout SAM file to be written as history item

tools/diamond/diamond.xml
The phrase 'reference genome' was confusing when using Diamond for proteomics. Also, the choice of query translation is not relevant for proteins. 
Finally, I changed the two sensitivity flag options to a select menu, to avoid possible option clash if someone is confused about how the options 'stack' (like I was) - see <https://github.com/bbuchfink/diamond/issues/160>.
=> Reduce genomics/proteomics clashes. Change sensitivity flags to select menu. 

tools/iprscan/interproscan.xml, tools/iprscan5/readme.rst, tools/sklearn/main_macros.xml, tools/staging_area/blast_unique_best_bit_score.xml, workflows/glimmer3/readme.rst, workflows/ncbi_blast_plus/find_genes_located_nearby/readme.rst, workflows/ncbi_blast_plus/find_three_genes_located_nearby/readme.rst
Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates some static DOI links that still point to the old resolver.
Cheers!
=> Link DOIs to preferred resolver

tools/sklearn/ensemble.xml, tools/sklearn/generalized_linear.xml, tools/sklearn/main_macros.xml
User is able to choose whether the input carry header or not. Support tabular data type only.
=> add header option for tabular data input

tools/rna_tools/rnacode/breakMAF.pl, tools/rna_tools/rnacode/processMAF.sh, tools/rna_tools/rnacode/rnacode.xml
Uses breakMAF.pl (from RNAcode package) to break the alignment into pieces. Unfortunately the perl script seems to be missing in the conda package. 
Of course we could also have a separate tool (but I don't see if splitting is interesting somewhere else).
=> optionally break maf in pieces before Rnacode call

tools/bismark/bismark_mapping/bismark_bowtie2_wrapper.xml, tools/bismark/bismark_mapping/bismark_wrapper.py
These fixes keep galaxy from trying to index the unsorted bam file produced by bismark.
Also fixes a stdout capture (w mode overwrites), and --upto support
=> Bismark datatype, fixes upto and stdout

tools/sklearn/clf_metrics.xml, tools/sklearn/ensemble.xml, tools/sklearn/feature_selection.xml, tools/sklearn/generalized_linear.xml, tools/sklearn/main_macros.xml, tools/sklearn/model_validation.xml, tools/sklearn/regression_metrics.xml
Provide multiple options on how to select data by column.
Choose `All columns` to skip column selection.
=> add column selector options for dataset input - able to input dataset without column selection

tools/sklearn/clf_metrics.xml, tools/sklearn/ensemble.xml, tools/sklearn/feature_selection.xml, tools/sklearn/generalized_linear.xml, tools/sklearn/main_macros.xml, tools/sklearn/model_validation.xml, tools/sklearn/regression_metrics.xml
Imagine there are hundreds or even thousands of features in the input dataset (e.g. RNAseq data) and only several columns, either index or labels, need be excluded from the column selection. This PR works perfectly for this kind of scenario.
=> add all-columns-but-by-index-number option to sklearn column selector

tools/racon/racon.xml
Changed the format from interval to tabular, this makes it able to use the newest minimap2 output.
=> Racon: Changed interval to tabular input format

tools/chipseeker/chipseeker.R, tools/chipseeker/chipseeker.xml
This is a fix for the tabular output headings, which currently has one of the peaks inserted e.g.:
`Chrom | Start | End | CDK12ChIP_bam_peak_1 | X17 | . | X2.39678 | X4.90017 | X1.75442 | X19 | annotation | geneChr | geneStart | geneEnd | geneLength | geneStrand | transcriptId | distanceToTSS | geneName | geneId`
this changes it to:
`Chrom | Start | End | V4 | V5 | V6 | V7 | V8 | V9 | V10 | annotation | geneChr | geneStart | geneEnd | geneLength | geneStrand | transcriptId | distanceToTSS | geneName | geneId`
(the V4 -V10 headings are due to R's naming, as there are no headings in the bed file input)
=> Chipseeker: fix for tabular output

tools/chipseeker/chipseeker.xml
- Added test to check if the tool runs when no plot output is selected
- Modified wrapper so that the test passes
=> Chipseeker raises error when 'no' is selected in the plots boolean

tools/text_processing/column_arrange_by_header/columnArrange.xml, tools/text_processing/column_arrange_by_header/column_arrange.py
This tool is currently not working on usegalaxy.eu because of a missing .so file of its pandas dependency.
I think it's better to avoid depending on pandas completely and work on a pure Python file iterator basis instead.
This makes the wrapper leaner and work with arbitrarily large input without any noticeable performance cost. In my testing of a 40,000 rows x 7 columns input, the pure Python implementation here finished faster than pandas could even be imported.
This PR also introduces a new ``--discard``parameter, which makes the tool equivalent to the Cut tool (just working with column names instead of indices), and it fixes an issue with quoting.
=> Column arrange update

.travis.yml, tools/chipseeker/.shed.yml, tools/chipseeker/chipseeker.R, tools/chipseeker/chipseeker.xml
- Found that chipseeker assumes a header is present in the input peaks file, unless the file has "bed" or related in the name (see here header https://github.com/GuangchuangYu/ChIPseeker/blob/master/R/readPeakFile.R#L60-L61), which was resulting in 1 peak/row of input not being output by this tool. So made an option for header, with default no header (assume most people would input BED)
- Fixed 2 plots that weren't being output in the PDF
- Fixed link to repo in shed.yml
=> Chipseeker: small fixes

tools/canu/canu.xml
Without M the value is taken as gigabyte, and `stopOnReadQuality` has been removed in 1.8.
=> Canu: append M to Galaxy Memory MB and bump to 1.8

tools/bismark/bismark_bowtie2_wrapper.xml
One last (:crossed_fingers:) PR to fix an issue with latest changes in bismark: errors when element_identifier contains spaces
=> Bismark: fix element_identifier sanitizing

tools/tool_recommendation_model/create_tool_recommendation_model.xml, tools/tool_recommendation_model/main.py
The loss input parameter was not needed as it is used in a derived form (weighted loss) and it is not required for users to change this error function
=> Remove loss type parameter

.travis.yml, tools/bismark/bismark_bowtie2_wrapper.xml
Just a little bugfix for "cannot find 'pbat' while searching for 'params.pbat'" error when not using the advanced options
=> bismark: fix error when not using advanced options

chemicaltoolbox/rdock/rbdock.xml
The `$score > 0` bits were stopping the score filter being applied when the value was negative.
=> fix problem with score filters not being applied

tools/salmon/alevin.xml
This PR makes a couple of tweaks to the Alevin wrapper's behaviour:
- Adds use of the undocumented 'freqThreshold' parameter, which has nevertheless been indicated to me a couple of times by the Alevin authors and is useful for our workflows.
- Adds the 'raw_cb_frequency.txt' output, which is what is triggered by supplying --dumpFeatures.
=> Alevin fixes for frequency and raw frequency output

tools/text_processing/text_processing/easyjoin.xml
Update to accept only tabular on the second file as well. With just accepting txt, there is no dropdown to select a column. Which is inconsistent as the first file does have this dropdown.
=> Update easy_join "Join two files"

tools/text_processing/text_processing/easyjoin.xml, tools/text_processing/text_processing/find_and_replace, tools/text_processing/text_processing/find_and_replace.xml
perl split defaults to split on any space but we need to split by tab
=> find_and_replace: column splitting bugfix

chemicaltoolbox/fpocket/fpocket.xml
Hi @bgruening !
I've modified fpocket. The PDB file *_out.pdb is the most important output (see page 31 of the fpocket manual to confirm - https://github.com/Discngine/fpocket/blob/master/doc/manual_fpocket2.pdf)
I've included this output and made sure that this and the all_verts output are selected by default. 
These two outputs are needed for visualisation of pockets and are used by the pymol and VMD visualisation scripts that are usually used with fpocket. 
Note that the PDB collection (atoms_output) does not contain the same information as found in *_out.pdb. This file is unique and important :smiley: Also updated the testcase.
All the best,
Chris
=> add the most important PDB output

chemicaltoolbox/xchem-deep/transfs.py, chemicaltoolbox/xchem-deep/transfs.xml
@bgruening Here is an initial attempt at an updated transfs tool.
The key change is that the user can choose from a number of models to use for the predictions.
Those models are present as files in the container in `/train/fragalysis_test_files/resources`.
There are 4 in total to choose from.
This obviously needs a new container image (`informaticsmatters/deep-app-ubuntu-1604:1.2`) that is a bit different from the one currently being used. The relevant files were moved from `/root/train/fragalysis_test_files` to `/train/fragalysis_test_files` and permissions on the files/dirs changed so that a normal user can run things. This means that most of your hacks to get round the original permissions problems won't be needed now, but I've not changed anything related to that, and I'm obviously …
=> transfs with multiple models

tools/cellprofiler/common.xml
because regex for file name was changed to 'field1....field6', these are cellprofiler metadata tags and must be made available for selection in the 'group category' parameter within "Group" section of common.xml
=> add metadata tags field1...6 to group category

tools/text_processing/text_processing/cut.xml
I have been getting a lot of reports from people getting stuck in tutorials because they are using this cut tool instead of the built-in one. 
Maybe renaming this tool would avoid confusion about which to use?
The problem arises because this tool does not rearrange columns if you specify e.g. "c2,c5,c3", but keeps them in order. In the ATAC-Seq tutorial for instance, this leads to an invalid BED file. (we could also update this tool to do the column rearranging like the other cut tool)
=> Change name of cut tool to avoid confusion with built-in cut tool

chemicaltoolbox/rdock/select_points_SDF.py, chemicaltoolbox/rdock/select_points_SDF.xml, chemicaltoolbox/rdock/test-data/select_points_output.sdf, chemicaltoolbox/rdock/test-data/select_points_output_v3000.sdf
This tool is meant to be used together with the rbcavity tool and it seems rbcavity is incredibly fussy about the formatting of the SD file and won't accept the files with the header that this tool was producing. :'(
=> Fix frankenstein ligand tool

tools/text_processing/text_processing/awk.xml
This commit: https://github.com/bgruening/galaxytools/commit/7bfc12bbe0f36602125eddde0e3b162ebe3345bf makes the corresponding biocontainer fall over with the kubernetes runner cause it uses Busybox's `awk` instead of `gawk`.
```
(base) BIOL-JT-ALEX:~ alex$ docker run -it --rm quay.io/biocontainers/gawk:4.2.0 'bash'
bash-4.2# env -i awk --help
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.
Usage: awk [OPTIONS] [AWK_PROGRAM] [FILE]...
-v VAR=VAL    Set variable
-F SEP        Use SEP as field separator
-f FILE        Read program from FILE
-e AWK_PROGRAM
bash-4.2# awk --help
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
POSIX options:        GNU long options: (standard)
-f progfile …
```
=> [awk] Using right awk in biocontainers

tools/text_processing/text_processing/sort_rows.xml
Containerized tool test was failing due to the old print. This makes it work. Alternative is to set py2 hard requirement potentially, but this print should be compatible with 2 and 3.
(This could be considered a paper-cut, but I can't set the label in this repo)
=> [tp_sort_rows] print py2->py3

tools/flye/flye.xml
Current version of flye doesn't work on fastq.gz files because it doesn't set the extension, this should fix that.
=> adding fastq.gz to flye ext parser

tools/flye/flye.xml, tools/flye/macros.xml
Genome size is no longer required, unless the --asm-coverage option is selected.
=> Update flye to 2.8.2

tools/rna_tools/graphprot/graphprot_predict_wrapper.py
Hi, I also added a lowercase input sequence check to the predict wrapper. Before the fix this caused the whole-site prediction to not output anything, although no error was thrown. Now tool terminates with assert, telling us what's wrong :+1:
=> added lc assert for ws predict

tools/rna_tools/miRDeep2/miRDeep2/mirdeep2.xml
Hello! This is an automated update of the following tool repo: **tools/rna_tools/miRDeep2/miRDeep2**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating tools/rna_tools/miRDeep2/miRDeep2 tool version(s)

chemicaltoolbox/silicos-it/qed/silicos_qed.xml
Hello! This is an automated update of the following tool repo: **chemicaltoolbox/silicos-it/qed**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
=> Updating chemicaltoolbox/silicos-it/qed tool version(s)

chemicaltoolbox/autodock_vina/prepare_box/prepare_box.xml
Update documentation of prepare_box tool to make it clear that files defining a protein pocket can be used as input, not just ligands.
I will update the training material as well.
ping @chrisbarnettster
=> Update prepare_box tool

tools/GraphClust/AlignCluster/align_cluster.xml, tools/GraphClust/CMFinder/cmFinder.xml, tools/GraphClust/GSPAN/fasta2shrep_gspan.xml, tools/GraphClust/LocARNAGraphClust/locarna_best_subtree.xml, tools/GraphClust/Structure_GSPAN/structure_to_gspan.xml
I didn't any datatype named `text`. Hence, changed from `format="text"` to `format="txt"`. Does it make sense?
=> fix: cmfinder writing to inputdir

tools/mafft/macros.xml
Hello! This is an automated update of the following tool: **tools/mafft**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/mafft from version 7.487 to 7.489.
=> Updating tools/mafft from version 7.487 to 7.489

tools/mafft/macros.xml
Hello! This is an automated update of the following tool: **tools/mafft**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/mafft from version 7.489 to 7.490.
=> Updating tools/mafft from version 7.489 to 7.490

chemicaltoolbox/autodock_vina/docking/docking.xml, chemicaltoolbox/autodock_vina/docking/test-data/ligand1_docked_flex.pdbqt, chemicaltoolbox/autodock_vina/docking/test-data/ligand2_docked_flex.pdbqt
Hello! This is an automated update of the following tool: **chemicaltoolbox/autodock_vina/docking**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated chemicaltoolbox/autodock_vina/docking from version 1.2.2 to 1.2.3.
**Project home page:** http://vina.scripps.edu
**Maintainers:** @simonbray
=> Updating chemicaltoolbox/autodock_vina/docking from version 1.2.2 to 1.2.3

tools/bionano/bionano_scaffold.xml
The tests contain assertions that stdout contains the exact text `attr="maxmem" val0="8"` for all test jobs.  Quite often this value will not be 8.  Update this and other values to assert that it matches an integer, not a specific integer.
=> update bionano_scaffold tests so that they do not fail based on values of 'threads' and 'memory'

tools/racon/macros.xml
Hello! This is an automated update of the following tool: **tools/racon**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/racon from version 1.4.20 to 1.5.0.
**Project home page:** https://github.com/isovic/racon/releases
=> Updating tools/racon from version 1.4.20 to 1.5.0

tools/mafft/macros.xml
Hello! This is an automated update of the following tool: **tools/mafft**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/mafft from version 7.490 to 7.505.
=> Updating tools/mafft from version 7.490 to 7.505

README.md, tools/sklearn/clf_metrics.xml, tools/sklearn/keras_macros.xml, tools/sklearn/to_categorical.xml
I am seeing a problem in ‘Create a deep learning model architecture’ tool, used in workflow for CNN tutorial: 
https://training.galaxyproject.org/training-material/topics/statistics/tutorials/CNN/tutorial.html
In 'Create a deep learning model architecture’ step of the tutorial, in layer 2, I have:
"padding='same'" for “Type in key words arguments if different from the default”
Any text argument (not just padding) fails to parse correctly, whether I use single or double quotes. I get the following error message for double quotes:
NameError
dict(padding=__dq__same__dq__)
^^^
name '__dq__same__dq__' is not defined
Traceback (most recent call last):
File "/jetstream2/scratch/test/jobs/1464482/tool_files/keras_deep_learning.py", line 397, in <module>
config_keras_model(inputs, outfile)
File …
=> Adding single and double quotes to valid values for key value args used in Keras tools.

tools/text_processing/split_file_on_column/split_file_on_column.xml, tools/text_processing/split_file_on_column/test-data/5cols-unsorted-with-header.tabular, tools/text_processing/split_file_on_column/test-data/5cols-unsorted.tabular
Working on a tutorial on data manipulation, and noticed this tool only works properly if the column was sorted (data was missing if unsorted, only the last cluster of consecutive rows with the certain value was present in the final file)
This adapts the tool to work for unsorted columns as well, and adds test cases.
=> [Split file on column] adapt tool to work on unsorted columns, add test cases

tools/sklearn/main_macros.xml, tools/sklearn/search_model_validation.xml
This PR fixes the issue: https://github.com/bgruening/galaxytools/issues/1231
Because of the unquoted @ symbol, most of the parameters of the selected estimator fail to load from a tubular file containing all parameters of the estimator.
Without the quoted @, the dropdown fails to load all the params, shown below:
EDIT: Removing @ for filtering estimator params fixes the issue
=> Fix issue with param loading and tool tests

tools/mafft/macros.xml
Hello! This is an automated update of the following tool: **tools/mafft**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/mafft from version 7.505 to 7.508.
For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).
=> Updating tools/mafft from version 7.505 to 7.508

tools/flye/flye.xml, tools/flye/macros.xml
Hello! This is an automated update of the following tool: **tools/flye**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/flye from version 2.9 to 2.9.1.
**Project home page:** https://github.com/fenderglass/Flye/releases
For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).
=> Updating tools/flye from version 2.9 to 2.9.1

tools/uniprot_rest_interface/uniprot.py, tools/uniprot_rest_interface/uniprot.xml
This allows the tool to keep being used until new code is written to utilize the new API, which requires submitting, polling, and fetching the results of an ID mapping job.
=> Use legacy URL for Uniprot 

tools/gfastats/gfastats.xml, tools/gfastats/macros.xml
hello! 👋🏼 
gfastats manipulation options were failing on hifiasm-generated GFA files due to those commands needing `--discover-paths`, which was not exposed as an option in the manipulation option of the previous tool wrapper. I have added this in
=> add `--discover` to manipulation option for gfastats

.github/workflows/pr.yaml
The following PR have not been deployed due to this bug (introduced here https://github.com/bgruening/galaxytools/pull/1264)
https://github.com/bgruening/galaxytools/pull/1269
https://github.com/bgruening/galaxytools/pull/1266
https://github.com/bgruening/galaxytools/pull/1263
Will bump the affected tools after this is merged
=> fix owner for CI deploy step

tools/sklearn/keras_macros.xml, tools/sklearn/keras_train_and_eval.py, tools/sklearn/keras_train_and_eval.xml
The PR adds an output dataset for displaying training logs if selected as a callback in the Keras model builder tool.
To use it, one needs to select the CSVLogger callback in the "Keras Model Builder" tool and then in the "Deep learning training and evaluation conduct deep training and evaluation either implicitly or explicitly", check the "Display CSVLogger if selected as a callback in the Keras model builder tool" checkbox. 
"Keras Model Builder" tool 
"Deep learning training and evaluation conduct deep training and evaluation either implicitly or explicitly" tool
ping @qiagu @kxk302. Can you look at this feature and provide your feedback?
Thanks
=> Output CSVLogger callback to a tabular file

tools/hifiasm/hifiasm.xml
hello! 👋🏼 
version bumping hifiasm to 0.19.7 which adds the `--dual-scaf` and `--scaf-gap` parameters as options. i've added these to the wrapper, too. i'm not sure what to do about tests, i tried running hifiasm on the existing test input files both with and without the `--dual-scaf` option and the results don't change 🤔
=> hifiasm: version bump 0.19.7, add scaff options to wrapper

tools/cellprofiler_v4/cellprofiler.xml, tools/cellprofiler_v4/macros.xml
Hello! This is an automated update of the following tool: **tools/cellprofiler_v4**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/cellprofiler_v4 from version 4.2.1 to 4.2.6.
For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).
=> Updating tools/cellprofiler_v4 from version 4.2.1 to 4.2.6

tools/hifiasm/hifiasm.xml
Hello! This is an automated update of the following tool: **tools/hifiasm**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.
I have updated tools/hifiasm from version 0.19.7 to 0.19.8.
**Project home page:** https://github.com/chhylp123/hifiasm/releases
For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).
=> Updating tools/hifiasm from version 0.19.7 to 0.19.8

tools/text_processing/split_file_to_collection/split_file_to_collection.py, tools/text_processing/split_file_to_collection/split_file_to_collection.xml
Allow chunksize to be greater than the number of records in the input file without raising the following error:
```
Traceback (most recent call last):
File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/6cbe2f30c2d7/split_file_to_collection/split_file_to_collection.py", line 281, in <module>
main()
File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/6cbe2f30c2d7/split_file_to_collection/split_file_to_collection.py", line 52, in main
split_by_record(args, in_file, out_dir, top, ftype)
File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/6cbe2f30c2d7/split_file_to_collection/split_file_to_collection.py", line 169, in split_by_record
new_file = …
```
=> Fix two bugs with `split_file_to_collection`

tools/nanopolish/macros.xml, tools/nanopolish/nanopolish_eventalign.xml, tools/nanopolish/nanopolish_methylation.xml, tools/nanopolish/nanopolish_polya.xml, tools/nanopolish/nanopolish_variants.xml
I attempted to address the following:
a) Existing version provides incorrect result (0 usable event detected) on a recent in-house project. Allegedly an issue that is nanopolish version-dependent.
b) Current wrapper does not explicitly handle input.fast5.tar.xz as input.
c) Current wrapper fails linting.
=> Update Nanopolish to v0.14

tools/rna_tools/rbpbench/macros.xml, tools/rna_tools/rbpbench/rbpbench.xml
This update should fix the cryptic meme version check error which currently occurs in the live version. Version check is now disabled, and rbpbench is setup to work specifically with meme version 5.5.4 which is set as requirement in macros.xml.
=> update v08 to fix meme version check error

tools/mcl/mcl.xml
This PR links mcl to its bio.tools [entry](https://bio.tools/mcl).
=> Added bio.tools ref to mcl

tools/flye/flye.xml, tools/flye/macros.xml
add biotools id to macros.xml and flye.xml
=> Flye biotools

tools/text_processing/text_processing/grep.xml, tools/text_processing/text_processing/macros.xml
fixes https://github.com/bgruening/galaxytools/issues/1412
=> Fixes for grep tool

tools/rna_tools/graphprot/graphprot_train_predict.xml
Hi, 
GraphProt on Galaxy currently does not work. I added the --gp-output to also get GraphProt log outputs, otherwise there is no way telling what the issue is. Offline GraphProt conda version fresh install works fine with the Galaxy python wrapper scripts, just tried.
Best,
Michael
=> add graphprot log output to find error in Galaxy version

tools/chatgpt/chatgpt.py, tools/chatgpt/chatgpt.xml
This pull request makes the question box required and provides a simple error message when the OpenAI API key is not provided in the user preferences.
=> Update ChatGPT tool

tools/text_processing/text_processing/cut.xml, tools/text_processing/text_processing/macros.xml, tools/text_processing/text_processing/sort_rows.xml
the list of columns must be after `-f` (or `-c` i.e. `cut_element`). I would have liked to add a test, but we can not use an option with the value `","` in a test (it will split it to a list of options `["", ""]`).
Still broken is that `data_column` parameters do not work for anything besides tab and comma separated values. Fixing this properly would require a restructuring of the tool form....
=> Fix cut tool

.gitignore
This PR updates the .gitignore file in the repository, aligning it with the .gitignore from the IUC [repository](https://github.com/galaxyproject/tools-iuc/blob/main/.gitignore). 
The changes address issue that occurred when trying to push files with certain extensions (e.g., .gz, .bz).
=> Updating .gitignore file

tools/flux/.shed.yml
The homepage URL for the flux tool was incorrect and pointed to the wrong location.
=> Fix homepage URL for flux tool

tools/flux/flux.py, tools/flux/flux.xml
Update for #1496
- Using model path insted of id to navigate to the latest snapshot avaiable.
- Adding logic to determine the number of inference steps based on the model name.
=> Refactor flux tool for improved model selection

tools/blobtoolkit/blobtoolkit.xml
The ftp url (ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/) of the taxdump is a broken link in the help section of the wrapper. The ftp link will be redirected to a ftp url with Galaxy prefix (i.e  https://usegalaxy.org.au/ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/) . I updated the broken ftp url with to https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/ instead of ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/ and it should work now.
Thanks
=> update ftp link in blobtoolkit.xml

tools/rna_tools/infernal/repository_dependencies.xml
AFAICT they are all in Galaxy now and we've deprecated loading TS datatypes a few years ago.
=> Drop datatype repository dependencies for infernal tools

tools/flux/flux.py, tools/flux/flux.xml
Enhance the output label based on the input type and include the prompt in the console output when using FLUX tool.
=> Improve FLUX tool for output label and prompt display

tools/splitfasta/.shed.yml, tools/splitfasta/splitFasta.xml, tools/splitfasta/split_fasta.py
I went with a default of unlimited but could also set some reasonable default if anyone has suggestions.
Additionally the tool will now use the sequence count (if available, although I believe it is [always available](https://github.com/galaxyproject/galaxy/blob/9fc0f0593517612f14c612c1648c2dc1a040f545/lib/galaxy/datatypes/sequence.py#L374)) from metadata rather than calculating it.
=> Add an admin-definable limit to the number of outputs rbc_splitfasta will create

tools/tabpfn/main.py, tools/tabpfn/tabpfn.xml
The PR adds:
- Appropriate license (in the help section)
- Comparison to CatBoost approach for classification and regression
=> TabPFN updates

tools/flexynesis/fetch_cbioportal_data.py, tools/flexynesis/flexynesis_cbioportal_import.xml, tools/flexynesis/macros.xml
this tool allows to import data from cBioPortal via studyID and prepare train/test datasets to use by flexynesis tool
=> add flexynesis_cbioportal_import

tools/diff/diff.xml, tools/diff/template.html
This PR replaces the default monospace font with `Noto Sans Mono CJK TC` for improved readability and better support for CJK characters (Chinese monospace font).
|Before|After|
|---|---|
|![before](https://github.com/user-attachments/assets/ed54c322-5fb8-44ed-9a55-b7bb7e7f9ee5)|![after](https://github.com/user-attachments/assets/3df93c97-3e71-4066-99f2-e2ce6df36721)|
=> Updates font stack for diff table

tools/trim_galore/macros.xml, tools/trim_galore/test-data/paired_collection_example_results3.txt, tools/trim_galore/test-data/paired_collection_example_results3gz.txt, tools/trim_galore/test-data/paired_example_results2.txt, tools/trim_galore/test-data/paired_example_results2gz.txt, tools/trim_galore/test-data/sanger_full_range_report_results1.txt, tools/trim_galore/test-data/sanger_full_range_report_results1gz.txt, tools/trim_galore/trim_galore.xml
version bump to 0.6.10 with updated tests; i tried to narrow down the diff checking a bit; each deviation seems to cause 2 hits (maybe because its the unified `diff -u`?), but some things can and should be variable (python version and number of cores, e.g.), and one line seems to randomly reorder itself (these vary in order: `(count smallRNA: 0, count Nextera: 0, count Illumina: 0)`)... but it may be too restrictive (other things might vary that i did not notice in my test runs; also will the underlying version of cutadapt change?)
=> trim_galore -> 0.6.10 with updated tests

tools/vpt/macros.xml, tools/vpt/vpt_segment.xml
the index which detects if a "," is needed after the bracket is correct now.
The z_index should be non-optional
=> fix vpt configuration and z_index param

tools/vpt/macros.xml, tools/vpt/vpt_segment.xml
If any channel is specified in the JSON config, then it should have a corresponding task_input_data parameter.
This update moves task_input_data under the image_channel so that they are bound together.
=> vpt - update test input data
